package br.com.cepedi.ShoppingStore.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "possible_facets")
public class PossibleFacets {
    
    // Primary key
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // Name of the possible facet
    @Column(name = "name")
    private String name;
    
    // Category ID associated with the possible facet
    @Column(name = "category_id")
    private Long categoryId;
    
    // Constructors, getters, and setters will be automatically generated by Lombok
}
